// Generated by CoffeeScript 1.8.0
(function() {
  var $, Z, _;

  _ = {};

  $ = this.$ = function(selector) {
    selector = selector.trim();
    return _.Z($.query(selector));
  };

  _.Z = function(dom) {
    return new Z(dom);
  };

  Z = function(dom) {
    var i, len;
    len = dom ? dom.length : 0;
    for (i in dom) {
      this[i] = dom[i];
    }
    this.length = len;
    return this;
  };

  $.ready = function(callback) {
    if (/complete|loaded|interactive/.test(document.readyState) && document.body) {
      callback($);
    } else {
      document.addEventListener('DOMContentLoaded', function() {
        return callback($);
      }, false);
    }
    return this;
  };

  $.isArraylike = function(obj) {
    return typeof obj.length === 'number';
  };

  $.query = function(selector) {
    var found, isSimple, maybeClass, maybeID, nameOnly, result, simpleSelectorRE, slice;
    slice = Array.prototype.slice;
    simpleSelectorRE = /^[\w-]*$/;
    result = null;
    found = [];
    maybeID = selector[0] === '#';
    maybeClass = !maybeID && selector[0] === '.';
    nameOnly = maybeID || maybeClass ? selector.slice(1) : selector;
    isSimple = simpleSelectorRE.test(nameOnly);
    if (document.getElementById && isSimple && maybeID) {
      if (found = document.getElementById(nameOnly)) {
        return result = [found];
      } else {
        return [];
      }
    } else {
      if (isSimple && !maybeID && document.getElementsByClassName) {
        if (maybeClass) {
          result = document.getElementsByClassName(nameOnly);
        } else {
          result = document.getElementsByTagName(selector);
        }
      } else {
        result = document.querySelectorAll(selector);
      }
      return result = slice.call(result);
    }
  };

  $.fn = {
    constructor: _.Z,
    author: 'bq',
    length: 0,
    forEach: [].forEach,
    reduce: [].reduce,
    push: [].push,
    sort: [].sort,
    splice: [].splice,
    indexOf: [].indexOf
  };

  _.Z.prototype = Z.prototype = $.fn;

  $._ = _;

}).call(this);

//# sourceMappingURL=index.js.map
